'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property CategoryTemplateId As Integer
    Public Property MetaKeywords As String
    Public Property MetaDescription As String
    Public Property MetaTitle As String
    Public Property ParentCategoryId As Integer
    Public Property PictureId As Integer
    Public Property PageSize As Integer
    Public Property AllowCustomersToSelectPageSize As Boolean
    Public Property PageSizeOptions As String
    Public Property PriceRanges As String
    Public Property ShowOnHomepage As Boolean
    Public Property IncludeInTopMenu As Boolean
    Public Property SubjectToAcl As Boolean
    Public Property LimitedToStores As Boolean
    Public Property Published As Boolean
    Public Property Deleted As Boolean
    Public Property DisplayOrder As Integer
    Public Property CreatedOnUtc As Date
    Public Property UpdatedOnUtc As Date

    Public Overridable Property Product_Category_Mapping As ICollection(Of Product_Category_Mapping) = New HashSet(Of Product_Category_Mapping)

End Class
