'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class db_numabunEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=db_numabunEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Pictures() As DbSet(Of Picture)
    Public Overridable Property PictureBinaries() As DbSet(Of PictureBinary)
    Public Overridable Property Products() As DbSet(Of Product)
    Public Overridable Property Product_Category_Mapping() As DbSet(Of Product_Category_Mapping)
    Public Overridable Property Product_Manufacturer_Mapping() As DbSet(Of Product_Manufacturer_Mapping)
    Public Overridable Property Product_Picture_Mapping() As DbSet(Of Product_Picture_Mapping)
    Public Overridable Property ShoppingCartItems() As DbSet(Of ShoppingCartItem)
    Public Overridable Property SO_Sales() As DbSet(Of SO_Sales)

End Class
