'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Picture
    Public Property Id As Integer
    Public Property MimeType As String
    Public Property SeoFilename As String
    Public Property AltAttribute As String
    Public Property TitleAttribute As String
    Public Property IsNew As Boolean
    Public Property VirtualPath As String

    Public Overridable Property PictureBinaries As ICollection(Of PictureBinary) = New HashSet(Of PictureBinary)
    Public Overridable Property Product_Picture_Mapping As ICollection(Of Product_Picture_Mapping) = New HashSet(Of Product_Picture_Mapping)

End Class
