'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property ProductTypeId As Integer
    Public Property ParentGroupedProductId As Integer
    Public Property VisibleIndividually As Boolean
    Public Property Name As String
    Public Property ShortDescription As String
    Public Property FullDescription As String
    Public Property AdminComment As String
    Public Property ProductTemplateId As Integer
    Public Property VendorId As Integer
    Public Property ShowOnHomepage As Boolean
    Public Property MetaKeywords As String
    Public Property MetaDescription As String
    Public Property MetaTitle As String
    Public Property AllowCustomerReviews As Boolean
    Public Property ApprovedRatingSum As Integer
    Public Property NotApprovedRatingSum As Integer
    Public Property ApprovedTotalReviews As Integer
    Public Property NotApprovedTotalReviews As Integer
    Public Property SubjectToAcl As Boolean
    Public Property LimitedToStores As Boolean
    Public Property Sku As String
    Public Property ManufacturerPartNumber As String
    Public Property Gtin As String
    Public Property IsGiftCard As Boolean
    Public Property GiftCardTypeId As Integer
    Public Property OverriddenGiftCardAmount As Nullable(Of Decimal)
    Public Property RequireOtherProducts As Boolean
    Public Property RequiredProductIds As String
    Public Property AutomaticallyAddRequiredProducts As Boolean
    Public Property IsDownload As Boolean
    Public Property DownloadId As Integer
    Public Property UnlimitedDownloads As Boolean
    Public Property MaxNumberOfDownloads As Integer
    Public Property DownloadExpirationDays As Nullable(Of Integer)
    Public Property DownloadActivationTypeId As Integer
    Public Property HasSampleDownload As Boolean
    Public Property SampleDownloadId As Integer
    Public Property HasUserAgreement As Boolean
    Public Property UserAgreementText As String
    Public Property IsRecurring As Boolean
    Public Property RecurringCycleLength As Integer
    Public Property RecurringCyclePeriodId As Integer
    Public Property RecurringTotalCycles As Integer
    Public Property IsRental As Boolean
    Public Property RentalPriceLength As Integer
    Public Property RentalPricePeriodId As Integer
    Public Property IsShipEnabled As Boolean
    Public Property IsFreeShipping As Boolean
    Public Property ShipSeparately As Boolean
    Public Property AdditionalShippingCharge As Decimal
    Public Property DeliveryDateId As Integer
    Public Property IsTaxExempt As Boolean
    Public Property TaxCategoryId As Integer
    Public Property IsTelecommunicationsOrBroadcastingOrElectronicServices As Boolean
    Public Property ManageInventoryMethodId As Integer
    Public Property ProductAvailabilityRangeId As Integer
    Public Property UseMultipleWarehouses As Boolean
    Public Property WarehouseId As Integer
    Public Property StockQuantity As Integer
    Public Property DisplayStockAvailability As Boolean
    Public Property DisplayStockQuantity As Boolean
    Public Property MinStockQuantity As Integer
    Public Property LowStockActivityId As Integer
    Public Property NotifyAdminForQuantityBelow As Integer
    Public Property BackorderModeId As Integer
    Public Property AllowBackInStockSubscriptions As Boolean
    Public Property OrderMinimumQuantity As Integer
    Public Property OrderMaximumQuantity As Integer
    Public Property AllowedQuantities As String
    Public Property AllowAddingOnlyExistingAttributeCombinations As Boolean
    Public Property NotReturnable As Boolean
    Public Property DisableBuyButton As Boolean
    Public Property DisableWishlistButton As Boolean
    Public Property AvailableForPreOrder As Boolean
    Public Property PreOrderAvailabilityStartDateTimeUtc As Nullable(Of Date)
    Public Property CallForPrice As Boolean
    Public Property Price As Decimal
    Public Property OldPrice As Decimal
    Public Property ProductCost As Decimal
    Public Property CustomerEntersPrice As Boolean
    Public Property MinimumCustomerEnteredPrice As Decimal
    Public Property MaximumCustomerEnteredPrice As Decimal
    Public Property BasepriceEnabled As Boolean
    Public Property BasepriceAmount As Decimal
    Public Property BasepriceUnitId As Integer
    Public Property BasepriceBaseAmount As Decimal
    Public Property BasepriceBaseUnitId As Integer
    Public Property MarkAsNew As Boolean
    Public Property MarkAsNewStartDateTimeUtc As Nullable(Of Date)
    Public Property MarkAsNewEndDateTimeUtc As Nullable(Of Date)
    Public Property HasTierPrices As Boolean
    Public Property HasDiscountsApplied As Boolean
    Public Property Weight As Decimal
    Public Property Length As Decimal
    Public Property Width As Decimal
    Public Property Height As Decimal
    Public Property AvailableStartDateTimeUtc As Nullable(Of Date)
    Public Property AvailableEndDateTimeUtc As Nullable(Of Date)
    Public Property DisplayOrder As Integer
    Public Property Published As Boolean
    Public Property Deleted As Boolean
    Public Property CreatedOnUtc As Date
    Public Property UpdatedOnUtc As Date

    Public Overridable Property Product_Category_Mapping As ICollection(Of Product_Category_Mapping) = New HashSet(Of Product_Category_Mapping)
    Public Overridable Property Product_Manufacturer_Mapping As ICollection(Of Product_Manufacturer_Mapping) = New HashSet(Of Product_Manufacturer_Mapping)
    Public Overridable Property Product_Picture_Mapping As ICollection(Of Product_Picture_Mapping) = New HashSet(Of Product_Picture_Mapping)
    Public Overridable Property ShoppingCartItems As ICollection(Of ShoppingCartItem) = New HashSet(Of ShoppingCartItem)

End Class
