'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SO_Sales
    Public Property ID As Integer
    Public Property STATION_ID As Nullable(Of Integer)
    Public Property TRANSACTION_ID As Nullable(Of Integer)
    Public Property TRANSACTION_DATE As Nullable(Of Date)
    Public Property TOTAL_VAT As Nullable(Of Integer)
    Public Property TOTAL_ORDER As Nullable(Of Double)
    Public Property DISCOUNT As Nullable(Of Double)
    Public Property TOTAL_FINAL As Nullable(Of Double)
    Public Property PAYMENT As String
    Public Property PAYMENT_ID As Nullable(Of Integer)
    Public Property STATUS_ORDER As Nullable(Of Integer)
    Public Property INFO_ORDER As String

End Class
